name: 測試用

on:
  workflow_dispatch :

jobs:
  fetch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install msgpack-lz4block
          pip install requests
          pip install pytz
          pip install UnityPy==1.10.18

      - name: 測試
        env:
          WDS_ENV_URL: ${{ secrets.WDS_ENV_URL }}
          WDS_MASTERLIST_URL: ${{ secrets.WDS_MASTERLIST_URL }}
          SCRIPT_VERSION: ${{ secrets.SCRIPT_VERSION }}
        run: |
          python ./code/fixcheck.py
      
      - name: update file and push to remote
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Test Update